CREATE DATABASE IF NOT EXISTS sheh CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sheh;
CREATE TABLE IF NOT EXISTS categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL,slug VARCHAR(120) NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS products(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(160) NOT NULL,slug VARCHAR(180) NOT NULL UNIQUE,short_description VARCHAR(500),full_description TEXT,price DECIMAL(10,2) NOT NULL,category_id INT,hero_image VARCHAR(255),texture_image VARCHAR(255),detail_image VARCHAR(255),usage_instructions TEXT,featured TINYINT(1) DEFAULT 0,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(category_id) REFERENCES categories(id));
CREATE TABLE IF NOT EXISTS ingredients(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(140) NOT NULL,short_benefit VARCHAR(255),description TEXT,image VARCHAR(255));
CREATE TABLE IF NOT EXISTS product_ingredients(id INT AUTO_INCREMENT PRIMARY KEY,product_id INT NOT NULL,ingredient_id INT NOT NULL,FOREIGN KEY(product_id) REFERENCES products(id) ON DELETE CASCADE,FOREIGN KEY(ingredient_id) REFERENCES ingredients(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS journal_posts(id INT AUTO_INCREMENT PRIMARY KEY,title VARCHAR(200) NOT NULL,slug VARCHAR(220) NOT NULL UNIQUE,excerpt VARCHAR(500),content LONGTEXT,cover_image VARCHAR(255),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contact_messages(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,email VARCHAR(180) NOT NULL,subject VARCHAR(200) NOT NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS admins(id INT AUTO_INCREMENT PRIMARY KEY,email VARCHAR(180) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
